service: expressAPI-eduapis
provider:
 name: aws
 runtime: nodejs12.x
 stage: dev
 region: ap-south-1
functions:
 eduapis:
   handler: index.eduapis
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'